apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d0oxgktxm-go 
  janus-idp.io/tekton: d0oxgktxm-go
  backstage.io/kubernetes-id: d0oxgktxm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d0oxgktxm-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml